### ISSUE TITLE
yambo-py

### ISSUE THREAD

**Issue by himanim92** [henriquemiranda/yambopy#17]
Dear all,
I am trying to use yambo-py but it is continously giving this error when i try to run a file named "gs_si.py" in the tutorial folder:
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       sitangshu-Veriton-M200-H81
Executable: pw.x

this is data I get in the relax.log file.
Please help.

**Comment by henriquemiranda** [comment]
To run the ground-state calculation you need to have the pw.x executable provided with the Quantum Espresso suite. You can download it in http://www.quantum-espresso.org/download/
